
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[482] =
    {   0,
       93,   91,   92,   92,   91,   92,   91,   92,   91,   92,
       56,   91,   92,   51,   91,   92,   91,   92,   39,   91,
       92,   40,   91,   92,   48,   91,   92,   46,   91,   92,
       44,   91,   92,   47,   91,   92,   55,   89,   91,   92,
       49,   91,   92,   87,   88,   91,   92,   87,   88,   91,
       92,   43,   91,   92,   45,   91,   92,   52,   91,   92,
       54,   91,   92,   53,   91,   92,   81,   91,   92,   86,
       88,   91,   92,   86,   88,   91,   92,   86,   88,   91,
       92,   86,   88,   91,   92,   41,   91,   92,   91,   92,
       42,   91,   92,   64,   91,   92,   86,   91,   92,   86,

       88,   91,   92,   86,   88,   91,   92,   86,   88,   91,
       92,   86,   88,   91,   92,   86,   88,   91,   92,   86,
       88,   91,   92,   86,   88,   91,   92,   86,   88,   91,
       92,   86,   88,   91,   92,   86,   88,   91,   92,   86,
       88,   91,   92,   86,   88,   91,   92,   86,   88,   91,
       92,   86,   88,   91,   92,   86,   88,   91,   92,   86,
       88,   91,   92,   57,   91,   92,   50,   91,   92,   58,
       91,   92,   63,   91,   92,    4,   91,   92,    3,16389,
       60,   90,    1,   72,   73,   90,   67,   70,   68,   69,
       83,   89,   79,   71,   89,   87,   88,   88,   88,   87,

       88,   87,   88,   85,   65,   61,   59,   62,   66,   82,
       86,   88,   86,   86,   88,   86,   88,   86,   88,    2,
        3,   75,   86,   88,   22,   86,   88,   86,   88,   86,
       88,   86,   88,   86,   88,   86,   88,   86,   88,   86,
       88,   86,   88,   86,   88,   86,   88,    8,   86,   88,
       86,   88,   16,   86,   88,   20,   86,   88,   86,   88,
       86,   88,   35,   86,   88,   86,   88,   86,   88,   86,
       88,   86,   88,   86,   88,   86,   88,   86,   88,   74,
        4,   90,   78,   84,   89,   80,   87,   88,   87,   87,
       76,   77,   86,   88,   86,   88,   86,   88,   18,   86,

       88,   86,   88,   86,   88,   86,   88,   86,   88,    7,
       86,   88,   11,   86,   88,   86,   88,   86,   88,   86,
       88,   86,   88,   31,   86,   88,   86,   88,   86,   88,
       86,   88,   86,   88,   86,   88,   32,   86,   88,   86,
       88,   86,   88,   86,   88,   17,   86,   88,   86,   88,
       86,   88,   86,   88, 8197,   87,   86,   88,   10,   86,
       88,   14,   86,   88,   86,   88,   86,   88,   86,   88,
       86,   88,   15,   86,   88,   19,   86,   88,   86,   88,
       86,   88,   34,   86,   88,   86,   88,   86,   88,   86,
       88,   86,   88,   38,   86,   88,   86,   88,   86,   88,

       86,   88,   25,   86,   88,   86,   88,   87,    6,   86,
       88,   86,   88,   30,   86,   88,   33,   86,   88,   86,
       88,   86,   88,   86,   88,   86,   88,   86,   88,   86,
       88,   86,   88,    9,   86,   88,   86,   88,   21,   86,
       88,   29,   86,   88,   26,   86,   88,   86,   88,   23,
       86,   88,   86,   88,   37,   86,   88,   12,   86,   88,
       24,   86,   88,   86,   88,   13,   86,   88,   86,   88,
       27,   86,   88,   86,   88,   36,   86,   88,   28,   86,
       88
    } ;

static const flex_int16_t yy_accept[244] =
    {   0,
        1,    1,    1,    2,    4,    5,    7,    9,   11,   14,
       17,   19,   22,   25,   28,   31,   34,   37,   41,   44,
       48,   52,   55,   58,   61,   64,   67,   70,   74,   78,
       82,   86,   89,   91,   94,   97,  100,  104,  108,  112,
      116,  120,  124,  128,  132,  136,  140,  144,  148,  152,
      156,  160,  164,  167,  170,  173,  176,  179,  180,  181,
      182,  182,  183,  183,  184,  185,  186,  186,  187,  188,
      189,  190,  191,  192,  192,  193,  193,  194,  195,  196,
      198,  199,  200,  202,  204,  204,  205,  206,  207,  208,
      209,  210,  211,  213,  214,  216,  218,  220,  221,  222,

      223,  225,  228,  230,  232,  234,  236,  238,  240,  242,
      244,  246,  248,  251,  253,  256,  259,  261,  263,  266,
      268,  270,  272,  274,  276,  278,  280,  281,  282,  282,
      283,  283,  283,  284,  285,  285,  286,  287,  289,  290,
      291,  292,  293,  295,  297,  299,  302,  304,  306,  308,
      310,  313,  316,  318,  320,  322,  324,  327,  329,  331,
      333,  335,  337,  340,  342,  344,  346,  349,  351,  353,
      355,  356,  356,  356,  356,  356,  356,  357,  359,  362,
      365,  367,  369,  371,  373,  376,  379,  381,  383,  386,
      388,  390,  392,  394,  397,  399,  401,  403,  406,  408,

      408,  408,  408,  408,  408,  408,  409,  412,  414,  417,
      420,  422,  424,  426,  428,  430,  432,  434,  437,  439,
      442,  445,  445,  445,  445,  445,  448,  450,  453,  455,
      458,  461,  464,  466,  469,  469,  469,  471,  474,  476,
      479,  482,  482
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,   25,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   29,   29,   30,   29,   29,
       29,   29,   29,   31,   29,   29,   29,   29,   29,   29,
       32,   33,   34,   35,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   29,   46,   47,   48,   49,
       50,   51,   29,   52,   53,   54,   55,   29,   56,   57,
       58,   29,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    4,    4,    1,
        1,    1,    1,    1,    1,    4,    4,    4,    5,    5,
        5,    1,    1,    1,    1,    6,    4,    4,    4,    4,
        4,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[259] =
    {   0,
        0,  497,  498,  500,   61,  474,  491,  492,  471,  470,
      483,  500,  500,   53,  468,  500,   43,   52,   52,   62,
       66,  467,  500,   50,  466,   63,  465,  451,   52,   41,
       38,  500,  483,  500,   81,    0,   56,   58,   61,   59,
       60,   70,   65,   82,   62,   77,   80,   89,   92,   85,
       98,   78,  500,  462,  500,  500,  482,  136,  481,  500,
      477,  476,  477,  500,  500,  500,  470,  469,  454,  500,
      500,  500,  500,  460,  122,  132,  452,  500,  134,  138,
      146,  458,  160,  153,  140,  500,  450,  500,  500,  500,
      449,  500,  435,    0,  108,  124,  112,  500,  468,  500,

      130,  132,  141,  144,  154,  168,  138,  156,  157,  169,
      158,  173,  433,  171,  432,  431,  176,  177,  430,  175,
      180,  178,  181,  182,  183,  193,  500,  463,  233,  500,
      459,  454,  500,  500,  222,  224,  500,  426,    0,  226,
      500,  500,  194,  197,  210,  425,  212,  213,  216,  218,
      424,  423,  219,  222,  223,  220,  422,  229,  230,  224,
      235,  231,  421,  234,  239,  240,  420,  243,  244,  246,
      500,  450,  449,  444,  443,    0,  415,  245,  414,  413,
      247,  100,  248,  249,  412,  411,  253,  255,  410,  260,
      262,  267,  269,  409,  270,  264,  272,  408,  281,  438,

      437,  436,  431,  430,  429,  401,  400,  273,  399,  398,
      274,  276,  279,  282,  284,  288,  292,  397,  286,  396,
      395,  364,  352,  345,  344,  314,  296,  313,  297,  312,
      311,  310,  300,  309,  339,  334,  298,  306,  305,  304,
      184,  500,  355,  361,  367,  371,  373,  376,  382,  388,
      180,  394,  400,   99,  406,  412,  418,  424
    } ;

static const flex_int16_t yy_def[259] =
    {   0,
      242,    1,  242,  242,  242,  242,  243,  244,  242,  242,
      245,  242,  242,  242,  242,  242,  242,  242,  242,  246,
      246,  242,  242,  242,  242,  242,  242,  247,  247,  247,
      247,  242,  242,  242,  242,  248,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  242,  242,  242,  242,  242,  242,  242,  242,
      243,  242,  244,  242,  242,  242,  245,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  246,
      246,  246,  246,  246,  242,  242,  242,  242,  242,  242,
      242,  242,  247,  248,  247,  247,  247,  242,  242,  242,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  242,  242,  242,  242,
      249,  250,  242,  242,  242,  242,  242,   83,  251,  242,
      242,  242,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      242,  252,  242,  253,  242,  254,  251,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  252,

      255,  242,  253,  256,  242,  251,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  257,  255,  258,  256,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  257,  258,  247,  247,  247,  247,
      247,    0,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242
    } ;

static const flex_int16_t yy_nxt[563] =
    {   0,
        4,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   28,   29,   28,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   28,   44,   28,   45,   28,   46,   47,
       48,   49,   28,   50,   28,   51,   28,   52,   53,   54,
       55,   56,   58,   59,   69,   72,   73,   74,   77,   75,
       75,   87,   88,   94,   78,   70,   94,   79,   76,   80,
       81,   79,   99,   84,   84,   90,   91,   94,   95,   97,
       96,   94,   76,   94,   94,   94,   94,   94,  117,  106,

       94,   85,  206,  100,  101,   94,  107,  104,  102,  103,
      105,  112,   94,   94,  109,   94,  108,   94,   83,  110,
       94,  111,  126,  113,   94,  120,  118,   94,  121,  114,
      115,  119,  122,   94,  116,   94,  123,   58,   59,   75,
       75,  124,  125,   94,  135,  209,  135,   94,   76,  136,
      136,   75,   75,   79,  143,   80,   81,  140,  140,   94,
       76,   79,   76,   81,   81,   94,  145,   94,   79,  146,
       84,   84,  144,   94,   76,  242,   94,  138,  138,   94,
      149,  148,  153,  177,  147,  138,  138,  138,   85,   94,
      154,   94,   94,   94,  155,  139,  138,  138,  138,  138,

      138,  138,  150,   94,   94,  156,   94,  158,   94,  151,
       94,   94,   94,   94,  152,   94,   94,   94,   94,   94,
      157,  160,  159,  161,  165,  162,  168,  164,   94,   94,
      163,  166,   94,  170,  129,  171,  169,  179,  167,  136,
      136,  136,  136,  140,  140,   94,  178,   94,   94,  182,
      180,   94,  181,   94,   94,   94,  188,   94,   94,   94,
      185,   85,  186,  187,   94,   94,   94,  190,  183,   94,
       94,  184,  192,  191,   94,   94,  189,  193,   94,   94,
       94,   94,   94,   94,   94,  207,  194,  198,   94,  197,
       94,  195,  199,  211,  196,   94,  214,   94,  208,   94,

      210,  213,   94,  212,   94,   94,  216,   94,   94,   94,
      218,   94,  220,  215,   94,  219,   94,   94,  217,   94,
      221,   94,  227,   94,  232,  229,  226,   94,  230,  228,
      233,   94,   94,   94,  234,   94,  239,  231,  240,   94,
       94,   94,  204,  201,   94,   94,   94,   94,   94,   94,
      237,  241,  130,  175,  238,   61,  130,   61,   61,   61,
       61,   63,   63,   63,   63,   63,   63,   67,  173,   67,
       67,   67,   67,   82,   82,   82,   93,   93,   93,   94,
       94,   94,  172,  172,  172,  172,  172,  172,  174,  174,
      174,  174,  174,  174,  200,  200,  200,  200,  200,  200,

      203,  203,  203,  203,  203,  203,  222,  222,  222,  222,
      222,  222,  224,  224,  224,  224,  224,  224,  235,  235,
      235,  235,  235,  235,  236,  236,  236,  236,  236,  236,
       94,   94,   94,   94,   94,   94,  176,  130,  225,  204,
      130,  223,  201,   94,   94,   94,   94,   94,   94,   94,
      176,  205,  204,  202,  201,   94,   94,   94,   94,   94,
       94,  176,  175,  173,  128,   94,   94,   94,   94,   99,
       94,  142,  141,  242,  137,  134,  133,  132,  130,   64,
      131,  130,  129,  128,  127,   98,   94,   92,   89,   86,
       71,   68,   66,   65,   64,   62,   60,  242,   57,    3,

      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242
    } ;

static const flex_int16_t yy_chk[563] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    5,   14,   17,   17,   18,   19,   18,
       18,   24,   24,   31,   19,   14,   30,   20,   18,   20,
       20,   21,   35,   21,   21,   26,   26,   29,   29,   31,
       30,   37,   18,   38,   40,   41,   39,   45,   45,   40,

       43,   21,  254,   35,   37,   42,   41,   39,   37,   38,
       39,   43,   46,   52,   42,   47,   41,   44,   20,   42,
       50,   42,   52,   44,   48,   48,   46,   49,   49,   44,
       44,   47,   49,   51,   44,  182,   50,   58,   58,   75,
       75,   51,   51,   95,   76,  182,   76,   97,   75,   76,
       76,   79,   79,   80,   95,   80,   80,   85,   85,   96,
       79,   81,   75,   81,   81,  101,   97,  102,   84,  101,
       84,   84,   96,  107,   79,   83,  103,   83,   83,  104,
      104,  103,  107,  251,  102,   83,   83,   83,   84,  105,
      107,  108,  109,  111,  108,   83,   83,   83,   83,   83,

       83,   83,  105,  106,  110,  109,  114,  111,  112,  106,
      120,  117,  118,  122,  106,  121,  123,  124,  125,  241,
      110,  114,  112,  117,  121,  118,  124,  120,  126,  143,
      118,  122,  144,  126,  129,  129,  125,  144,  123,  135,
      135,  136,  136,  140,  140,  145,  143,  147,  148,  148,
      145,  149,  147,  150,  153,  156,  156,  154,  155,  160,
      153,  140,  154,  155,  158,  159,  162,  159,  149,  164,
      161,  150,  161,  160,  165,  166,  158,  162,  168,  169,
      178,  170,  181,  183,  184,  178,  164,  169,  187,  168,
      188,  165,  170,  184,  166,  190,  190,  191,  181,  196,

      183,  188,  192,  187,  193,  195,  192,  197,  208,  211,
      195,  212,  197,  191,  213,  196,  199,  214,  193,  215,
      199,  219,  211,  216,  216,  213,  208,  217,  214,  212,
      217,  227,  229,  237,  219,  233,  233,  215,  237,  240,
      239,  238,  236,  235,  234,  232,  231,  230,  228,  226,
      227,  239,  225,  224,  229,  243,  223,  243,  243,  243,
      243,  244,  244,  244,  244,  244,  244,  245,  222,  245,
      245,  245,  245,  246,  246,  246,  247,  247,  247,  248,
      248,  248,  249,  249,  249,  249,  249,  249,  250,  250,
      250,  250,  250,  250,  252,  252,  252,  252,  252,  252,

      253,  253,  253,  253,  253,  253,  255,  255,  255,  255,
      255,  255,  256,  256,  256,  256,  256,  256,  257,  257,
      257,  257,  257,  257,  258,  258,  258,  258,  258,  258,
      221,  220,  218,  210,  209,  207,  206,  205,  204,  203,
      202,  201,  200,  198,  194,  189,  186,  185,  180,  179,
      177,  175,  174,  173,  172,  167,  163,  157,  152,  151,
      146,  138,  132,  131,  128,  119,  116,  115,  113,   99,
       93,   91,   87,   82,   77,   74,   69,   68,   67,   63,
       62,   61,   59,   57,   54,   33,   28,   27,   25,   22,
       15,   11,   10,    9,    8,    7,    6,    3,    2,  242,

      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "punylex.l"
/* -*-bison-*- */
/* Simple wc implementation in Flex */
#define YY_NO_INPUT 1
#line 8 "punylex.l"
#include "token.h"
#include "defs.h"
int dentstack[100]={0};
int top=0;
int indentlevel(char *s);		
int rows = 1, words = 0, column=0;
int dedentcount;
int firsttime;

#define yylex real_yylex			
#line 735 "lex.yy.c"
#line 736 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 29 "punylex.l"


#line 963 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 243 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 500 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 31 "punylex.l"
{ rows++; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 32 "punylex.l"
{ if (firsttime++ == 0) return ENDMARKER; else return -1; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 33 "punylex.l"
{ rows++; column=1; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 34 "punylex.l"
{ 	
                            int il = indentlevel(yytext+1);
                            rows++; column=il+1;
                            if (il > dentstack[top]) {
                                dentstack[++top] = il;
                                /* return an INDENT token, except NEWLINE first */
                                dedentcount = -1;
                                for(int i = 0; i < strlen(yytext); i++) printf("%d ", yytext[i]);
                                printf(": indent generated on line %d\n", rows);
                            }
                            else if (il < dentstack[top]) {
                                /* return one or more DEDENT tokens */
                                dedentcount=0;
                                /* count how many */
                                while (top>0 && dentstack[top]>il) {
                                    dedentcount++; top--; 
                                    for(int i = 0; i < strlen(yytext); i++) printf("%d ", yytext[i]);
                                    printf(": dedent generated on line %d\n", rows);
                                }
                                if (dentstack[top] != il) {
                                    fprintf(stderr, "Python indent error line %d\n", rows);
                                    fflush(stderr); exit(1);
                                }
                                /* need to dedent by dedentcount, but returning NEWLINE */
                            }
                            else {
                                /* still at ILEVEL il, no INDENT or DEDENT */
                            
                            }
                            return NEWLINE; 
                        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 65 "punylex.l"
{
                    if(rows == 1) {
                        fprintf(stderr, "Unexpected indent on line 1\n");
                        exit(1);
                    }
                }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 72 "punylex.l"
{ rows += 2; printf("nihil: %d?\n", rows); column = 1;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 74 "punylex.l"
{ column += strlen(yytext); words++; return PYFALSE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 75 "punylex.l"
{ column += strlen(yytext);words++; return PYDEF; } 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 76 "punylex.l"
{ column += strlen(yytext);words++; return IF; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 77 "punylex.l"
{ column += strlen(yytext);words++; return RAISE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 78 "punylex.l"
{ column += strlen(yytext);words++; return NONE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 79 "punylex.l"
{ column += strlen(yytext);words++; return DEL; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 80 "punylex.l"
{ column += strlen(yytext);words++; return IMPORT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 81 "punylex.l"
{ column += strlen(yytext);words++; return RETURN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 82 "punylex.l"
{ column += strlen(yytext);words++; return PYTRUE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 83 "punylex.l"
{ column += strlen(yytext);words++; return ELIF; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 84 "punylex.l"
{ column += strlen(yytext);words++; return IN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 85 "punylex.l"
{ column += strlen(yytext);words++; return TRY; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 86 "punylex.l"
{ column += strlen(yytext);words++; return AND; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 87 "punylex.l"
{ column += strlen(yytext);words++; return ELSE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 88 "punylex.l"
{ column += strlen(yytext);words++; return IS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 89 "punylex.l"
{ column += strlen(yytext);words++; return WHILE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 90 "punylex.l"
{ column += strlen(yytext);words++; return AS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 91 "punylex.l"
{ column += strlen(yytext);words++; return EXCEPT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 92 "punylex.l"
{ column += strlen(yytext);words++; return LAMBDA; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 93 "punylex.l"
{ column += strlen(yytext);words++; return WITH; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 94 "punylex.l"
{ column += strlen(yytext);words++; return ASSERT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 95 "punylex.l"
{ column += strlen(yytext);words++; return FINALLY; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 96 "punylex.l"
{ column += strlen(yytext);words++; return NONLOCAL; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 97 "punylex.l"
{ column += strlen(yytext);words++; return YIELD; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 98 "punylex.l"
{ column += strlen(yytext);words++; return BREAK; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 99 "punylex.l"
{ column += strlen(yytext);words++; return FOR; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 100 "punylex.l"
{ column += strlen(yytext);words++; return NOT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 101 "punylex.l"
{ column += strlen(yytext);words++; return CLASS; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 102 "punylex.l"
{ column += strlen(yytext);words++; return FROM; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 103 "punylex.l"
{ column += strlen(yytext);words++; return OR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 104 "punylex.l"
{ column += strlen(yytext);words++; return CONTINUE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 105 "punylex.l"
{ column += strlen(yytext);words++; return GLOBAL; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 106 "punylex.l"
{ column += strlen(yytext);words++; return PASS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 107 "punylex.l"
{ column += strlen(yytext); return LPAR; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 108 "punylex.l"
{ column += strlen(yytext); return RPAR; }					                     
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 109 "punylex.l"
{ column += strlen(yytext); return LSQB; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 110 "punylex.l"
{ column += strlen(yytext); return RSQB; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 111 "punylex.l"
{ column += strlen(yytext); return COLON; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 112 "punylex.l"
{ column += strlen(yytext); return COMMA; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 113 "punylex.l"
{ column += strlen(yytext); return SEMI; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 114 "punylex.l"
{ column += strlen(yytext); return PLUS; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 115 "punylex.l"
{ column += strlen(yytext); return MINUS; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 116 "punylex.l"
{ column += strlen(yytext); return STAR; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 117 "punylex.l"
{ column += strlen(yytext); return SLASH; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 118 "punylex.l"
{ column += strlen(yytext); return VBAR; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 119 "punylex.l"
{ column += strlen(yytext); return AMPER; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 120 "punylex.l"
{ column += strlen(yytext); return LESS; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 121 "punylex.l"
{ column += strlen(yytext); return GREATER; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 122 "punylex.l"
{ column += strlen(yytext); return EQUAL; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 123 "punylex.l"
{ column += strlen(yytext); return DOT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 124 "punylex.l"
{ column += strlen(yytext); return PERCENT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 125 "punylex.l"
{ column += strlen(yytext); return LBRACE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 126 "punylex.l"
{ column += strlen(yytext); return RBRACE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 127 "punylex.l"
{ column += strlen(yytext); return EQEQUAL; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 128 "punylex.l"
{ column += strlen(yytext); return NOTEQUAL; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 129 "punylex.l"
{ column += strlen(yytext); return LESSEQUAL; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 130 "punylex.l"
{ column += strlen(yytext); return GREATEREQUAL; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 131 "punylex.l"
{ column += strlen(yytext); return TILDE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 132 "punylex.l"
{ column += strlen(yytext); return CIRCUMFLEX; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 133 "punylex.l"
{ column += strlen(yytext); return LEFTSHIFT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 134 "punylex.l"
{ column += strlen(yytext); return RIGHTSHIFT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 135 "punylex.l"
{ column += strlen(yytext); return DOUBLESTAR; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 136 "punylex.l"
{ column += strlen(yytext); return PLUSEQUAL; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 137 "punylex.l"
{ column += strlen(yytext); return MINEQUAL; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 138 "punylex.l"
{ column += strlen(yytext); return STAREQUAL; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 139 "punylex.l"
{ column += strlen(yytext); return SLASHEQUAL; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 140 "punylex.l"
{ column += strlen(yytext); return PERCENTEQUAL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 141 "punylex.l"
{ column += strlen(yytext); return AMPEREQUAL; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 142 "punylex.l"
{ column += strlen(yytext); return VBAREQUAL; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 143 "punylex.l"
{ column += strlen(yytext); return CIRCUMFLEXEQUAL; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 144 "punylex.l"
{ column += strlen(yytext); return LEFTSHIFTEQUAL; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 145 "punylex.l"
{ column += strlen(yytext); return RIGHTSHIFTEQUAL; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 146 "punylex.l"
{ column += strlen(yytext); return DOUBLESTAREQUAL; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 147 "punylex.l"
{ column += strlen(yytext); return DOUBLESLASH; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 148 "punylex.l"
{ column += strlen(yytext); return DOUBLESLASHEQUAL; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 149 "punylex.l"
{ column += strlen(yytext); return AT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 150 "punylex.l"
{ column += strlen(yytext); return ATEQUAL; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 151 "punylex.l"
{ column += strlen(yytext); return RARROW; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 152 "punylex.l"
{ column += strlen(yytext); return ELLIPSIS; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 153 "punylex.l"
{ column += strlen(yytext); return COLONEQUAL; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 154 "punylex.l"
{ column += strlen(yytext); return NAME; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 155 "punylex.l"
{ column += strlen(yytext); return INTLIT; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 156 "punylex.l"
{column += strlen(yytext); words++; return NAME;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 157 "punylex.l"
{ column += strlen(yytext); return FLOATLIT; }
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 158 "punylex.l"
{
                int len = strlen(yytext);
                char c;
                for(int i = 0; i < len; i++) {
                    c = *(yytext + i);
                    column++;
                    if(c == '\n') {
                        rows++;
                        column = 1;
                    }
                }
                return STRINGLIT;
            }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 171 "punylex.l"
{column++;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 172 "punylex.l"
ECHO;
	YY_BREAK
#line 1560 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 243 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 243 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 242);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 172 "punylex.l"



int indentlevel(char *s)
{      
   int column = 1;
   while(*s != '\0') {
      if (*s == '\t') {
         while ((column % 8) != 0) column++;
      }
      else if (*s == ' ') column++;
      else { column++; printf("but wtf is %c\n", *s);}
      s++;
   }
   return column-1;
}

#undef yylex

int yylex() {
   if (dedentcount<0) {
     dedentcount++;
     return INDENT;
     }
   if(dedentcount>0) {
     dedentcount--;
     return DEDENT;
     }
   return real_yylex();
}




